### ISSUE TITLE
Debería leer un docker.env para la config

### ISSUE THREAD

**Issue by sergiovier** [SIU-Toba/docker-certs#2]
Hoy lee directamente el docker-template.env y debería comportarse igual que en el resto de los docker que exigen un docker.env (viene de copiar el docker-template.env y editarlo). Debería estar en el .gitignore también.

**Comment by enfoqueNativo** [comment]
Es cierto, por homogeneidad con los otros containers deberia estar asi. En cuanto pueda lo cambio, graciela! :+1:

**Comment by enfoqueNativo** [comment]
Listo el pollo.
